name: RChat
version: 1.0
main: org.rcbox.rchat.Rchat
api-version: 1.13

depend: [Vault]

commands:
  g:
    description: Global Chat
    usage: /g [message]
  l:
    description: Local Chat
    usage: /l [message]
  s:
    description: Staff Chat
    usage: /l [message]
    permission: rchat.staff
    permission-message: You don't have access to Staff Chat.
